schema_version: 1

context:
  version: "0.2.2"
  python_min: "3.10"

package:
  name: python-serafin
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-serafin/python_serafin-${{ version }}.tar.gz
  sha256: bed92a701dd8efde6fe84a7c73d97afc7c8da9635de034ed6cf41b4e3dbcb82e

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.24

tests:
  - python:
      imports:
        - serafin
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Read and write Serafin (TELEMAC) binary files
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://gitlab.com/isl-ingenierie/modules-python/python-serafin
  repository: https://gitlab.com/isl-ingenierie/modules-python/python-serafin

extra:
  recipe-maintainers:
    - nicogodet
    - tomsail
